//MOVIES & SERIES ACTIONS
export const GET_CARDS_INIT = "GET_CARDS_INIT";
export const GET_CARDS_DONE = "GET_CARDS_DONE";
export const GET_CARDS_FAILED = "GET_CARDS_FAILED";

// MOVIES
export const GET_LATEST_MOVIES = "GET_LATEST_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_MOST_VOTED_MOVIES = "GET_MOST_VOTED_MOVIES";

// SERIES
export const GET_ON_THE_AIR_SERIES = "GET_ON_THE_AIR_SERIES";
export const GET_TOP_RATED_SERIES = "GET_TOP_RATED_SERIES";
export const GET_MOST_POPULAR_SERIES = "GET_MOST_POPULAR_SERIES";
