//MOVIES & SERIES ACTIONS
export const GET_CARDS_INIT = "GET_CARDS_INIT";
export const GET_CARDS_FAILED = "GET_CARDS_FAILED";

// MOVIES
export const GET_LATEST_MOVIES = "GET_LATEST_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_MOST_VOTED_MOVIES = "GET_MOST_VOTED_MOVIES";
export const GET_MOVIES_CARDS_DONE = "GET_MOVIES_CARDS_DONE";

// SERIES
export const GET_ON_THE_AIR_SERIES = "GET_ON_THE_AIR_SERIES";
export const GET_TOP_RATED_SERIES = "GET_TOP_RATED_SERIES";
export const GET_MOST_POPULAR_SERIES = "GET_MOST_POPULAR_SERIES";
export const GET_SERIES_CARDS_DONE = "GET_SERIES_CARDS_DONE";

// SINGLE MOVIE/SERIE (MEDIA)
export const GET_MEDIA_INIT = "GET_MEDIA_INIT";
export const GET_MEDIA = "GET_MEDIA";
export const GET_MEDIA_DONE = "GET_MEDIA_DONE";
export const GET_MEDIA_FAILED = "GET_MEDIA_FAILED";

// SEARCHBAR
export const SEARCHBAR_INIT = "SEARCHBAR_INIT";
export const SEARCHBAR_DONE = "SEARCHBAR_DONE";
export const SEARCHBAR_FAILED = "SEARCHBAR_FAILED";
export const SEARCHBAR_RESET = "SEARCHBAR_RESET";
