//MOVIES & SERIES ACTIONS
export const GET_CARDS_INIT = "GET_CARDS_INIT";
export const GET_CARDS_FAILED = "GET_CARDS_FAILED";

// MOVIES
export const GET_LATEST_MOVIES = "GET_LATEST_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_MOST_VOTED_MOVIES = "GET_MOST_VOTED_MOVIES";
export const GET_MOVIES_CARDS_DONE = "GET_MOVIES_CARDS_DONE";

// SERIES
export const GET_ON_THE_AIR_SERIES = "GET_ON_THE_AIR_SERIES";
export const GET_TOP_RATED_SERIES = "GET_TOP_RATED_SERIES";
export const GET_MOST_POPULAR_SERIES = "GET_MOST_POPULAR_SERIES";
export const GET_SERIES_CARDS_DONE = "GET_SERIES_CARDS_DONE";

// SINGLE MOVIE/SERIE (MEDIA)
export const GET_MEDIA_INIT = "GET_MEDIA_INIT";
export const GET_MEDIA = "GET_MEDIA";
export const GET_MEDIA_DONE = "GET_MEDIA_DONE";
export const GET_MEDIA_FAILED = "GET_MEDIA_FAILED";

// SEARCHBAR
export const SEARCHBAR_INIT = "SEARCHBAR_INIT";
export const SEARCHBAR_DONE = "SEARCHBAR_DONE";
export const SEARCHBAR_FAILED = "SEARCHBAR_FAILED";
export const SEARCHBAR_RESET = "SEARCHBAR_RESET";

// AUTH
export const AUTHENTICATION_INIT = "AUTHENTICATION_INIT";
export const AUTHENTICATION_SUCCEEDED = "AUTHENTICATION_SUCCEEDED";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const AUTHENTICATION_RESET = "AUTHENTICATION_RESET";
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const FETCH_CURRENT_USER_FAILED = "FETCH_CURRENT_USER_FAILED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// REGISTRATION
export const REGISTRATION_INIT = "REGISTRATION_INIT";
export const REGISTRATION_SUCCEEDED = "REGISTRATION_SUCCEEDED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

// FAVORITES
export const FAVORITES_INIT = "FAVORITES_INIT";
export const GET_FAVORITED_MOVIES = "GET_FAVORITED_MOVIES";
export const GET_FAVORITED_MOVIES_SUCCEEDED = "GET_FAVORITED_MOVIES_SUCCEEDED";
export const GET_FAVORITED_MOVIES_FAILED = "GET_FAVORITED_MOVIES_FAILED";
export const GET_FAVORITED_SERIES = "GET_FAVORITED_SERIES";
export const GET_FAVORITED_SERIES_SUCCEEDED = "GET_FAVORITED_SERIES_SUCCEEDED";
export const GET_FAVORITED_SERIES_FAILED = "GET_FAVORITED_SERIES_FAILED";
export const IS_FAVORITED = "IS_FAVORITED";
export const SET_IS_FAVORITED = "SET_IS_FAVORITED";
export const ADD_TO_FAVORITES_SUCCEEDED = "ADD_TO_FAVORITES_SUCCEEDED";
export const ADD_TO_FAVORITES_FAILED = "ADD_TO_FAVORITES_FAILED";
export const REMOVE_FROM_FAVORITES_SUCCEEDED =
  "REMOVE_FROM_FAVORITES_SUCCEEDED";
export const REMOVE_FROM_FAVORITES_FAILED = "REMOVE_FROM_FAVORITES_FAILED";

// LIKES
export const LIKES_INIT = "LIKES_INIT";
export const GET_LIKED_MOVIES = "GET_LIKED_MOVIES";
export const GET_LIKED_MOVIES_SUCCEEDED = "GET_LIKED_MOVIES_SUCCEEDED";
export const GET_LIKED_MOVIES_FAILED = "GET_LIKED_MOVIES_FAILED";
export const GET_LIKED_SERIES = "GET_LIKED_SERIES";
export const GET_LIKED_SERIES_SUCCEEDED = "GET_LIKED_SERIES_SUCCEEDED";
export const GET_LIKED_SERIES_FAILED = "GET_LIKED_SERIES_FAILED";
export const IS_LIKED = "IS_LIKED";
export const SET_IS_LIKED = "SET_IS_LIKED";
export const ADD_TO_LIKES_SUCCEEDED = "ADD_TO_LIKES_SUCCEEDED";
export const ADD_TO_LIKES_FAILED = "ADD_TO_LIKES_FAILED";
export const REMOVE_FROM_LIKES_SUCCEEDED = "REMOVE_FROM_LIKES_SUCCEEDED";
export const REMOVE_FROM_LIKES_FAILED = "REMOVE_FROM_LIKES_FAILED";
