module.exports = {
  TMDB_API_KEY: process.env.TMDB_API_KEY,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_KEY: process.env.CLOUDINARY_SECRET_KEY,
  SENDGRID: process.env.SENDGRID,
  JWT_SECRET: process.env.JWT_SECRET
};
